[pytest]

testpaths = tests

pythonpath = .

python_files = test_*.py

addopts = --alluredir=allure-results --clean-alluredir --headed --screenshot=only-on-failure

filterwarnings =
    ignore::pytest.PytestUnknownMarkWarning

markers =
    only: маркер для запуска конкретного теста

